# Generated by Django 4.2.27 on 2025-12-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcv',
            name='ats_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
