# Generated by Django 4.2.27 on 2025-12-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_uploadcv_ats_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rematch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(default=None, max_length=255, null=True, upload_to='rematch_cvs/')),
                ('extracted_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ats_score', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
