# Generated by Django 4.2.25 on 2025-12-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_rematch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rematch',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='rematch',
            name='extracted_text',
        ),
        migrations.AddField(
            model_name='rematch',
            name='ideal_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
